{% set name = "vinca" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: '{{ version }}.{{ datetime.datetime.strftime(datetime.datetime.now(), "%Y%m%d") }}'

source:
  git_url: https://github.com/ros-forge/vinca.git
  git_rev: master

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools
    - catkin_pkg >=0.4.16
    - ruamel.yaml >=0.16.6
    - rosdistro >=0.8.0
    - empy >=3.3.4
  run:
    - catkin_pkg >=0.4.16
    - ruamel.yaml >=0.16.6
    - rosdistro >=0.8.0
    - empy >=3.3.4

#test:
#  commands:
#    - vinca -h

about:
  home: https://github.com/ros-forge/vinca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A generator for ROS conda recipes

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
